/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LawIndexRouteImport } from './routes/law.index'
import { Route as InterpretationsIndexRouteImport } from './routes/interpretations.index'
import { Route as LawArticleNumberRouteImport } from './routes/law.$articleNumber'
import { Route as InterpretationsIdRouteImport } from './routes/interpretations.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LawIndexRoute = LawIndexRouteImport.update({
  id: '/law/',
  path: '/law/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterpretationsIndexRoute = InterpretationsIndexRouteImport.update({
  id: '/interpretations/',
  path: '/interpretations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LawArticleNumberRoute = LawArticleNumberRouteImport.update({
  id: '/law/$articleNumber',
  path: '/law/$articleNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const InterpretationsIdRoute = InterpretationsIdRouteImport.update({
  id: '/interpretations/$id',
  path: '/interpretations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/interpretations/$id': typeof InterpretationsIdRoute
  '/law/$articleNumber': typeof LawArticleNumberRoute
  '/interpretations/': typeof InterpretationsIndexRoute
  '/law/': typeof LawIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/interpretations/$id': typeof InterpretationsIdRoute
  '/law/$articleNumber': typeof LawArticleNumberRoute
  '/interpretations': typeof InterpretationsIndexRoute
  '/law': typeof LawIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/interpretations/$id': typeof InterpretationsIdRoute
  '/law/$articleNumber': typeof LawArticleNumberRoute
  '/interpretations/': typeof InterpretationsIndexRoute
  '/law/': typeof LawIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/interpretations/$id'
    | '/law/$articleNumber'
    | '/interpretations/'
    | '/law/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/interpretations/$id'
    | '/law/$articleNumber'
    | '/interpretations'
    | '/law'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/interpretations/$id'
    | '/law/$articleNumber'
    | '/interpretations/'
    | '/law/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  InterpretationsIdRoute: typeof InterpretationsIdRoute
  LawArticleNumberRoute: typeof LawArticleNumberRoute
  InterpretationsIndexRoute: typeof InterpretationsIndexRoute
  LawIndexRoute: typeof LawIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/law/': {
      id: '/law/'
      path: '/law'
      fullPath: '/law/'
      preLoaderRoute: typeof LawIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interpretations/': {
      id: '/interpretations/'
      path: '/interpretations'
      fullPath: '/interpretations/'
      preLoaderRoute: typeof InterpretationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/law/$articleNumber': {
      id: '/law/$articleNumber'
      path: '/law/$articleNumber'
      fullPath: '/law/$articleNumber'
      preLoaderRoute: typeof LawArticleNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interpretations/$id': {
      id: '/interpretations/$id'
      path: '/interpretations/$id'
      fullPath: '/interpretations/$id'
      preLoaderRoute: typeof InterpretationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  InterpretationsIdRoute: InterpretationsIdRoute,
  LawArticleNumberRoute: LawArticleNumberRoute,
  InterpretationsIndexRoute: InterpretationsIndexRoute,
  LawIndexRoute: LawIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
